### ISSUE TITLE
How about the robust of this method

### ISSUE THREAD

**Issue by gerrardmai** [lanjiangboston/GiniClust#2]
same dataset, if I have select different numbers of high GINI value gene (pvalue 0.01, and 0.001), cannot get the same (similar) rare celltype group.

**Comment by lanjiangboston** [comment]
Hi gerrardmai,
Thanks for your question. The default value for the parameter p-value for UMI based RNA-seq data is 0.0001. With the data in our hands, the clustering results are quite robust for a range of epsilon. Of cause, you can tune the parameters and it is can be expected that you will get different results, especially for p-value. By the way, may I ask which platform your dataset is generated from?

Best,
Lan

**Comment by Tsinghua-gongjing** [comment]
Hi, Lan,

Thank you for the work. In the sample directory you have provided two data set (GBM and qPCR), does it possible to also upload the other three data sets you used in the GiniClust paper?

Thanks,
Jing

**Comment by gcyuan** [comment]
Hi Jing

Thank you for using GiniClust. All the datasets can be downloaded directly from the original publications, as described in our GiniClust paper. 

 Best
Guo-Cheng

**Comment by Tsinghua-gongjing** [comment]
That's great, I'll look into the details, thanks.

Best,
Jing
