### ISSUE TITLE
Error Running GiniClust - filter function

### ISSUE THREAD

**Issue by Cassalhoo** [lanjiangboston/GiniClust#3]
When I run Giniclust with my dataset It stop in the filter function.

My data are avaliable: 
https://drive.google.com/drive/u/0/folders/1_07OCDjC9WL-MfUWGe5At_wP0G6wtjqG

**Comment by rdong08** [comment]
I am Rui from GC Yuan's lab. It seems like there's conflict of "filter" function between "MAST" and "stats" packages in R. You can add package name before "filter" with "::" to solve this problem. If you could share your code, it would be better. Thanks.

**Comment by Cassalhoo** [comment]
Hi Rui,
Thank you for your reply.
When I run GiniClust using the sample dataset (Data_GBM.csv) using the command line:

Rscript GiniClust_Main.R -f Data_GBM.csv -t RNA-seq -o GBM_results

The code works fine  and I don't receive any error messages.

 
After that, I tried to use my dataset as a parameter with the following command line:

Rscript GiniClust_Main.R -f GSE36552_table.csv -t RNA-seq -o GSE36552_results

When I use my dataset as a parameter the program execution is interrupted when the script is running the filter task.
What do you think? Do you have any insights about it?

Thanks once again.

**Comment by rdong08** [comment]
Hi Cassalhoo,

I tested the dataset you use and found GiniClust works on your dataset. GiniClust will report a cluster result file in your output directionally. If you could not find "GSE36552_results /GSE36552_table.csv_clusterID.csv" you can try GiniClust2.
