### ISSUE TITLE
Calls: GiniClust_Fitting ... calcul.gini -> drop -> crossprod -> crossprod -> <Anonymous>

### ISSUE THREAD

**Issue by alessandriLuca** [lanjiangboston/GiniClust#4]
Hi, im trying this clustering algorithm but i have the following error : 
Calls: GiniClust_Fitting ... calcul.gini -> drop -> crossprod -> crossprod -> <Anonymous>
The matrix that I use is an RNa-seq matrix, comma separated, csv and raw count data. Do you know which one could be the problem?
[test.zip](https://github.com/lanjiangboston/GiniClust/files/3697152/test.zip)

**Comment by lanjiangboston** [comment]
Hi,
your input file, for example, the test.zip, has a small problem with the format.  You can use the code as following to fix it. 
ExprM  <- read.csv("test.csv", sep=",", head=T)
rownames(ExprM)= ExprM[,1]
ExprM= ExprM[,-1]
write.table(ExprM, file="new_test.csv", sep=",", row.names = TRUE, col.names = TRUE, quote=FALSE)
Please feel free to let me know if you have further questions.

Best,
Lan
